{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "task-manager.fullname" . }}
  labels:
    {{- include "task-manager.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "task-manager.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetMemoryUtilizationPercentage }}
  behavior:
    scaleUp:
      stabilizationWindowSeconds: {{ .Values.autoscaling.behavior.scaleUp.stabilizationWindowSeconds }}
      policies:
        - type: Pods
          value: {{ .Values.autoscaling.behavior.scaleUp.pods.value }}
          periodSeconds: {{ .Values.autoscaling.behavior.scaleUp.pods.periodSeconds }}
        - type: Percent
          value: {{ .Values.autoscaling.behavior.scaleUp.percent.value }}
          periodSeconds: {{ .Values.autoscaling.behavior.scaleUp.percent.periodSeconds }}
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: {{ .Values.autoscaling.behavior.scaleDown.stabilizationWindowSeconds }}
      policies:
        - type: Pods
          value: {{ .Values.autoscaling.behavior.scaleDown.pods.value }}
          periodSeconds: {{ .Values.autoscaling.behavior.scaleDown.pods.periodSeconds }}
      selectPolicy: Min
{{- end }}
